language: java
jdk:
- oraclejdk11
env:
- _JAVA_OPTIONS="-Dtestfx.robot=awt"

addons:
    sonarcloud:
        organization: alessandrasonsini
        token: 5902fbc08c17a4f42eb0a8c90556f83d9f27ebef


script:
- ant build
- sonar-scanner
