language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: alessandrasonsini
    token: 5902fbc08c17a4f42eb0a8c90556f83d9f27ebef

script:
- mvn -X clean install
- sonar-scanner
