language: java
jdk:
	- openjdk8
before_install:
    - sudo apt install -y openjfx
addons:
    sonarcloud:
        organization: alessandrasonsini
        token: 5902fbc08c17a4f42eb0a8c90556f83d9f27ebef
        
script:
	- ant build
	- sonar-scanner
